### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by MikUwU** [alexandrelam/among-legends#9]
- [ ] Faire qu'on ne puisse voter qu'une fois et pas soi-même
- [ ] Faire apparaitre le scoreboard et le role des joueurs une fois que tt le monde a voté
- [ ] Enlever les joueurs de l'équipe adverse dans le vote
- [ ] Enlever le reveal des role de la commande /win
